version: '3.8'
services:
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: usererp
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: dogu4891..00
    ports:
      - "3307:3306"

  app:
    image: usererp-springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usererp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dogu4891..00
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      - db
  react:
    image: usererp-react
    ports:
      - "5174:5173"
    depends_on:
      - app